[workspace]
resolver = "2"

members = [
    "myt2abrp",
    "myt",
]


[workspace.dependencies]
serde = { version = "1.0.218", features = ["derive"]}
serde_json = { version = "1.0.142" }
bytes = "1.10.0"
spin-sdk = "3.1.0"
