[workspace]
resolver = "2"

members = [
    "myt2abrp",
    "myt",
]


[workspace.dependencies]
serde = { version = "1.0.217", features = ["derive"]}
serde_json = { version = "1.0.134" }
bytes = "1.9.0"
spin-sdk = "3.1.0"
