[workspace]
resolver = "2"

members = [
    "myt2abrp",
    "myt",
]


[workspace.dependencies]
serde = { version = "1.0.192", features = ["derive"]}
serde_json = { version = "1.0.132" }
bytes = "1.8.0"
spin-sdk = "3.0.1"
